### ISSUE TITLE
example usage throws an error

### ISSUE THREAD

**Issue by seizethedata** [categulario/map_matching#19]
Hey there,

I'm trying to execute the example request from readme - I had to fix the name from mapmatching to mapmatch, by the way: `./main.py mapmatch data/route.geojson 5`, but it throws an error: `processing layer 1
Traceback (most recent call last):
  File "./main.py", line 328, in <module>
    val = locals()[args.task](*args.args)
  File "/Users/ecco/map_matching-master/lib/__init__.py", line 24, in wrapper
    return f(*args, **kwds)
  File "./main.py", line 139, in mapmatch
    parent.skip_node if parent is not None else None
  File "/Users/ecco/map_matching-master/lib/__init__.py", line 24, in wrapper
    return f(*args, **kwds)
  File "./main.py", line 281, in lua
    return red.evalsha(sha, 0, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/client.py", line 2829, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/client.py", line 838, in execute_command
    conn.send_command(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 686, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 737, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 118, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
`

I have also tried it with example points and with my own points - ./main.py mapmatch data/points.geojson 500 -, and had this error:

`
Traceback (most recent call last):
  File "./main.py", line 328, in <module>
    val = locals()[args.task](*args.args)
  File "/Users/ecco/map_matching-master/lib/__init__.py", line 24, in wrapper
    return f(*args, **kwds)
  File "./main.py", line 108, in mapmatch
    lua('ways_from_gps', RADIUS, *coords) for coords in coordinates
  File "./main.py", line 108, in <listcomp>
    lua('ways_from_gps', RADIUS, *coords) for coords in coordinates
TypeError: lua() argument after * must be an iterable, not float`

Would be great if you addressed this issue.
Thanks in advance!

**Comment by categulario** [comment]
thanks for the report. I'll take a look

**Comment by categulario** [comment]
hey, I just pushed some changes, basically everything changed. Take a look and re-read the readme. If you have any questions I'm here to help

**Comment by seizethedata** [comment]
Abraham, thanks, I've managed to execute the example code, but it seems to work with glitches. Some parts of the track snaps fine, some of it way off the track. See pictures below. 


![Screen Shot 2020-01-09 at 17 52 21](https://user-images.githubusercontent.com/29729619/72145275-37fd6900-33ab-11ea-8daa-90b1517b2f1e.png)
![Screen Shot 2020-01-09 at 17 51 58](https://user-images.githubusercontent.com/29729619/72145276-37fd6900-33ab-11ea-8208-45e6cb7231e3.png)



Also, when trying to snap a relly short track in Moscow, Russia, I've waited around 5-6 hours and it still didn't finish the execution, so I've dropped it. I have 20gb of RAM and i5 processor, so I guess the problem is not on my side.

ALSO, works only for tracks (lines), not working for points.

**Comment by categulario** [comment]
Unfortunately the algorithm still needs a little bit of tunning for some parameters to work better. In the case of Russia you need to download from openstreetmaps all the streets in the bounding box of the tracks that you're trying to match. If the information is not complete there might be cases in which the A* algorithm gets stuck.

**Comment by zkyf** [comment]
i got the same problem on data in china. since there are chinese characters in road names, i added `encoding='utf-8'` to main.py in line 32, 71, 118 and 130.  then i use the tool as:
```
mapmatching download 120.1147385 30.245226 120.2094425 30 .314329999999998 -o streets.json
mapmatching load -f streets.json
```
everything seems work till here without error. i manually draw a polyline in geojson format and save it as route.json and get the error:
```
> mapmatching match route.geojson -o output.json
Traceback (most recent call last):
  File "G:\Codes\envs\py356torch110\Scripts\mapmatching-script.py", line 11, in <module>
    load_entry_point('mapmatching==0.1.4', 'console_scripts', 'mapmatching')()
  File "G:\Codes\envs\py356torch110\lib\site-packages\mapmatching-0.1.4-py3.5.egg\mapmatching\main.py", line 166, in main
    args.func(args)
  File "G:\Codes\envs\py356torch110\lib\site-packages\mapmatching-0.1.4-py3.5.egg\mapmatching\task.py", line 59, in wrapper
    return obj.execute(*new_args, **kwds)
  File "G:\Codes\envs\py356torch110\lib\site-packages\mapmatching-0.1.4-py3.5.egg\mapmatching\main.py", line 148, in execute
    args.radius,
  File "G:\Codes\envs\py356torch110\lib\site-packages\mapmatching-0.1.4-py3.5.egg\mapmatching\match.py", line 66, in match
    parent.skip_node if parent is not None else 'None'
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\client.py", line 3745, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\client.py", line 2829, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\client.py", line 838, in execute_command
    conn.send_command(*args)
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\connection.py", line 686, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\connection.py", line 737, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "G:\Codes\envs\py356torch110\lib\site-packages\redis\connection.py", line 118, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
```


just solved by modifying match.py line 66 to:
`parent.skip_node if (parent is not None) and (parent.skip_node is not None) else 'None'`

**Comment by categulario** [comment]
yeah, that fixes it, be welcome to make a PR with your patch and I'll include it in the next release
